// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function ShowWindow():Promise<void>;
