// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Fetch'](arg1, arg2, arg3, arg4);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
